// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "autoSync": boolean;
      "realtimeUpdates": boolean;
      "syncOnStartup": boolean;
      "showSharedAnnotations": boolean;
      "showPrivateAnnotations": boolean;
      "maxAnnotations": number;
      "requestTimeout": number;
      "debugMode": boolean;
      "input": string;
    };
  }
}
