// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-account-title'
  | 'pref-auto-sync'
  | 'pref-auto-upload'
  | 'pref-email-label'
  | 'pref-help'
  | 'pref-logged-in-text'
  | 'pref-login-btn'
  | 'pref-login-title'
  | 'pref-logout-btn'
  | 'pref-password-label'
  | 'pref-settings-title'
  | 'pref-show-notifications'
  | 'pref-title'
  | 'researchopia-annotations-header'
  | 'researchopia-annotations-sidenav'
  | 'startup-begin'
  | 'startup-finish';
