// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "autoSync": boolean;
      "realtimeUpdates": boolean;
      "syncOnStartup": boolean;
      "showSharedAnnotations": boolean;
      "showPrivateAnnotations": boolean;
      "readerIntegration": boolean;
      "showUserAvatars": boolean;
      "maxAnnotations": number;
      "sortMethod": string;
      "annotationOpacity": number;
      "enableLikes": boolean;
      "enableComments": boolean;
      "enableFollows": boolean;
      "enableNotifications": boolean;
      "annotationVisibility": string;
      "requestTimeout": number;
      "syncInterval": number;
      "cacheSize": number;
      "debugMode": boolean;
      "offlineMode": boolean;
      "autoShare": boolean;
      "input": string;
    };
  }
}
