// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "autoUploadAnnotations": boolean;
      "showNotifications": boolean;
      "customSearch": boolean;
      "userEmail": string;
      "isLoggedIn": boolean;
      "rememberCredentials": boolean;
      "savedEmail": string;
      "savedPassword": string;
    };
  }
}
