// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'researchopia-button-comment'
  | 'researchopia-button-extract'
  | 'researchopia-button-like'
  | 'researchopia-button-share'
  | 'researchopia-button-view'
  | 'researchopia-description'
  | 'researchopia-item-section-head-text'
  | 'researchopia-item-section-sidenav-tooltip'
  | 'researchopia-menu-extract'
  | 'researchopia-menu-share'
  | 'researchopia-menu-view'
  | 'researchopia-message-error'
  | 'researchopia-message-extracting'
  | 'researchopia-message-loading'
  | 'researchopia-message-sharing'
  | 'researchopia-message-success'
  | 'researchopia-name'
  | 'researchopia-prefs-auto-share'
  | 'researchopia-prefs-debug'
  | 'researchopia-prefs-enable'
  | 'researchopia-prefs-notifications'
  | 'researchopia-prefs-supabase-key'
  | 'researchopia-prefs-supabase-url'
  | 'researchopia-prefs-title'
  | 'researchopia-status-connected'
  | 'researchopia-status-connecting'
  | 'researchopia-status-error'
  | 'researchopia-status-ready';
