// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "supabaseUrl": string;
      "supabaseKey": string;
      "autoShare": boolean;
      "showNotifications": boolean;
      "debugMode": boolean;
    };
  }
}
